%YAML:1.0
#File.version: 1.0
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 707.0912
Camera.fy: 707.0912
Camera.cx: 601.8873
Camera.cy: 183.1104

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.bFishEye: 0

Camera.width: 1226
Camera.height: 370

# Camera frames per second
Camera.fps: 10.0

# stereo baseline times fx
Camera.bf: 379.8145

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Transformation from camera 0 to body-frame (imu)
Tbc: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  # data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
  #       0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
  #      -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
  #       0.0, 0.0, 0.0, 1.0]
  data: [ -0.0010886,-0.0085120,0.9999632,1.1438987008758374,
          -0.9999764,-0.0067777,-0.0011463,-0.3127184548305896,
          0.0067872,-0.9999408,-0.0085044,0.7265461471096181,
          0.0, 0.0, 0.0, 1.0 ]
# IMU noise
IMU.NoiseGyro: 1.6968e-04 #1.6968e-04
IMU.NoiseAcc: 2.0000e-3 #2.0e-3
IMU.GyroWalk: 0.003491
IMU.AccWalk: 5.0000e-3 # 3e-03
IMU.Frequency: 100

loopClosing: 0
#--------------------------------------------------------------------------------------------
# LiDAR Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
LiDAR.enabled: 1
LiDAR.wLBA: 0.01

Tcl: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  # data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
  #       0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
  #      -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
  #       0.0, 0.0, 0.0, 1.0]
  data: [ 7.027555e-03, -9.999753e-01, 2.599616e-05, -7.137748e-03,-2.254837e-03, -4.184312e-05, -9.999975e-01, -7.482656e-02,9.999728e-01, 7.027479e-03, -2.255075e-03, -3.336324e-01,0.0, 0.0, 0.0, 1.0 ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 12
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2
Viewer.GraphLineWidth: 1
Viewer.PointSize: 2
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -100
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000

