%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 721.5377
Camera.fy: 721.5377
Camera.cx: 609.5593
Camera.cy: 172.854

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1241
Camera.height: 376

# Camera frames per second
Camera.fps: 10.0

# stereo baseline times fx
Camera.bf: 387.5744

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0
loopClosing: 0
#--------------------------------------------------------------------------------------------
# LiDAR Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
LiDAR.enabled: 1
LiDAR.wLBA: 1.0

Tcl: !!opencv-matrix
rows: 4
cols: 4
dt: f
# data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
#       0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
#      -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
#       0.0, 0.0, 0.0, 1.0]
data: [ 7.533745e-03, -9.999714e-01, -6.166020e-04, -4.069766e-03, 1.480249e-02, 7.280733e-04, -9.998902e-01,-7.631618e-02, 9.998621e-01, 7.523790e-03, 1.480755e-02,-2.717806e-01,0.0, 0.0, 0.0, 1.0 ]


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2
Viewer.GraphLineWidth: 1
Viewer.PointSize:2
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -100
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000

